### ISSUE TITLE
flaky test related to an `Unexpected Event: Debug, Resume`

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/vm_service_drivers#193]
```
[java] Log info: VM message: {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"PauseExit","isolate":{"type":"@Isolate","fixedId":true,"id":"isolates\/577385908","name":"sample_main.dart:main()","number":"577385908"},"timestamp":1541100941522}}}
     [java] ****** Unexpected Event: Debug, Resume
     [java] Log info: VM connection closed: ws://localhost:7576/ws
     [java] Exception in thread "main" java.lang.RuntimeException: Expected event: Debug, Resume
     [java] 	at org.dartlang.vm.service.SampleVmServiceListener.waitFor(Unknown Source)
     [java] 	at org.dartlang.vm.service.VmServiceTest.finishExecution(Unknown Source)
     [java] 	at org.dartlang.vm.service.VmServiceTest.runSample(Unknown Source)
     [java] 	at org.dartlang.vm.service.VmServiceTest.main(Unknown Source)
     [java] Terminated sample process
```

**Comment by devoncarew** [comment]
I haven't seen this flake for a while...
