### ISSUE TITLE
CI for the java tests has regressed

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/vm_service_drivers#238]
https://travis-ci.org/dart-lang/vm_service_drivers/jobs/527387562

**Comment by devoncarew** [comment]
Some details:
- travis has moved to Java 11
- our websocket library depends on a class from a module that is now no longer loaded in the jdk by default
- we'll need to update the websocket library to not use this class, or switch to a different websocket library

**Comment by devoncarew** [comment]
```
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
     [java] 	at de.roderick.weberknecht.WebSocketHandshake.encodeBase64String(WebSocketHandshake.java:113)
     [java] 	at de.roderick.weberknecht.WebSocketHandshake.createNonce(WebSocketHandshake.java:109)
     [java] 	at de.roderick.weberknecht.WebSocketHandshake.<init>(WebSocketHandshake.java:36)
     [java] 	at de.roderick.weberknecht.WebSocket.<init>(WebSocket.java:86)
     [java] 	at de.roderick.weberknecht.WebSocket.<init>(WebSocket.java:76)
     [java] 	at org.dartlang.vm.service.VmServiceBase.connect(VmServiceBase.java:67)
```

https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j

**Comment by devoncarew** [comment]
We may want to move to a different websocket client library - perhaps https://github.com/TooTallNate/Java-WebSocket ?
